apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

commonLabels:
  environment: staging
  team: backend

resources:
  - ../../base

replicas:
  - name: wordpress
    count: 2