apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

commonLabels:
  environment: development
  team: backend

resources:
  - ../../base

replicas:
  - name: wordpress
    count: 1