apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: v1-  # convenience field

# Warning: 'commonLabels' is deprecated. Please use 'labels' instead.
commonLabels:    # convenience field
  version : v1
  environment: dev

resources:
  - ../base