apiVersion: v1
kind: Namespace
metadata:
  name: starbucks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee
  namespace: starbucks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
        - name: coffee
          image: nginxdemos/nginx-hello:plain-text
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-svc 
  namespace: starbucks  
spec:
  selector:
    app: coffee
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
