default:
  env:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=otel-demo"

components:
  accounting: false
  ad: false
  cart: true
  checkout: false
  currency: false
  email: false
  fraud-detection: false
  frontend:
    service:
      type: ClusterIP
  load-generator: false
  payment: false
  product-catalog: true
  recommendation: false
  shipping: false
