apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

commonLabels:
  environment: production
  team: backend

resources:
  - ../../base

replicas:
  - name: wordpress
    count: 5